######################################################################
# Automatically generated by qmake (3.1) Sun May 24 11:30:39 2026
######################################################################

QT += gui widgets core network networkauth
TEMPLATE = app
TARGET = trakt-qt
INCLUDEPATH += .
DESTDIR = build
MOC_DIR = build
OBJECTS_DIR = build

HEADERS += mainwindow.hpp \
        awesome.hpp \
        traktclient.hpp \
        loginview.hpp \
        homeview.hpp \
        searchview.hpp \
        showdetailsview.hpp \
        infowidget.hpp \
        loadingdialog.hpp \
        seasonswidget.hpp \
        episodewidget.hpp \
        collapsablewidget.hpp \
        sectionwidget.hpp \
        episodeswidget.hpp

SOURCES += main.cpp \
        mainwindow.cpp \
        traktclient.cpp \
        loginview.cpp \
        homeview.cpp \
        searchview.cpp \
        showdetailsview.cpp \
        infowidget.cpp \
        loadingdialog.cpp \
        seasonswidget.cpp \
        episodewidget.cpp \
        collapsablewidget.cpp \
        sectionwidget.cpp \
        episodeswidget.cpp

RESOURCES += resources.qrc

CONFIG+=fontAwesomeFree
include(QtAwesome/QtAwesome.pri)
